name: Code Quality Check

on: [push, pull_request]

jobs:
  code_quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up GitHub Super-Linter
        uses: github/super-linter@v4
        with:
          # Include specific languages and directories you want to lint
          languages: python, javascript
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ github.sha }}
        
